# Site settings
title: Anaxiatech AB
email: theresia.lundgren@anaxiatech.se
description: AI-powered solutions for infrastructure analysis
baseurl: ""
url: "https://anaxiatech.se"

# Build settings
markdown: kramdown
plugins:
- jekyll-feed

# Exclude files
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
